#!/bin/bash
source ./submitParamsSteno.txt

CMD=$1
IN=$2

# default values
NCPUS=1
MEM=2
# read options
shift 2
while getopts "c:m:v:" OPTION; do
    case $OPTION in
    c)
        NCPUS=${OPTARG};;
    m)
        MEM=${OPTARG};;
    a)
        ARG=${OPTARG};;
    *)  
        echo "Incorrect options provided"
        exit 1
        ;;
    esac
done

EXTRA=""
# Gaussian specific options
if [ $CMD == "gaussian" ]; then
    # check if gaussian environment variables are set
    if [[ -z "${GAUSS_EXE}" ]]; then
        echo "GAUSS_EXE is not set"
        exit 1
    else
        CMD=$GAUSS_EXE
    fi
    if [[ -z "${GAUSS_EXEDIR}" ]]; then
        echo "GAUSS_EXEDIR is not set"
        exit 1
    fi
    if [[ -z "${GAUSS_SCRDIR}" ]]; then
        echo "GAUSS_SCRDIR is not set"
        exit 1
    fi
    # update parmameters in Gaussian input file
    sed -i -e "s/mem=.*/mem=${MEM}GB/g" -e "s/nprocshared=.*/nprocshared=$NCPUS/g" $IN
    EXTRA+="export GAUSS_EXEDIR=${GAUSS_EXEDIR}
export GAUSS_SCRDIR=${GAUSS_SCRDIR}"
elif [ $CMD == "python" ]; then
    # use current python environment
    PYTHON=`which python`
    CMD=$PYTHON 
    CMD+=" -u"
else
    echo "Unknown command: $CMD"
    exit 1
fi

# get the filename without the extension
JOB=${IN%.*}

echo "Submitting $IN with $CMD to $PARTITION using $NCPUS cores and $MEM GB memory"

SUBMIT=qsub.tmp
cat > $SUBMIT << !EOF
#!/bin/sh
#SBATCH --job-name=$JOB
#SBATCH --cpus-per-task=$NCPUS
#SBATCH --ntasks=1
#SBATCH --error=$JOB\_%j.err
#SBATCH --output=$JOB\_%j.out
#SBATCH --time=$TIME
#SBATCH --partition=$PARTITION
#SBATCH --no-requeue
#SBATCH --mem=${MEM}GB

$EXTRA

srun $CMD $IN $ARG> $JOB.out
!EOF

sbatch $SUBMIT
rm $SUBMIT